# SEE: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#common-application-properties

server:
    address: 127.0.0.1
    port: 9000

---

spring:
    profiles: development
server:
    port: 8080

---

spring:
    profiles: production
server:
    port: 0
